# Generated by Django 3.0.5 on 2020-04-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descripccion',
            field=models.TextField(),
        ),
    ]
